services:

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-soc

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: sentinel
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin123

    volumes:
      - clickhouse-data:/var/lib/clickhouse

    restart: unless-stopped

volumes:
  clickhouse-data: