import { useParams } from "react-router-dom";

import { useInvestigation } from "@/hooks/useInvestigation";

import SummaryCard from "@/components/investigation/SummaryCard";
import TimelineCard from "@/components/investigation/TimelineCard";
import RecommendationsCard from "@/components/investigation/RecommendationsCard";
import ConfidenceCard from "@/components/investigation/ConfidenceCard";

export default function Investigation() {
  const { id } = useParams();

  const {
    data,
    isLoading,
    error,
  } = useInvestigation(id!);

  if (isLoading) {
    return (
      <div className="text-white">
        Running AI investigation...
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="text-red-400">
        Failed to load investigation.
      </div>
    );
  }

  return (
    <div className="space-y-6">

      <div>
        <h1 className="text-3xl font-bold">
          AI Security Investigation
        </h1>

        <p className="text-slate-400">
          Generated by {data.model}
        </p>
      </div>

      <ConfidenceCard
        confidence={data.confidence}
      />

      <SummaryCard
        title="Executive Summary"
        content={data.executive_summary}
      />

      <SummaryCard
        title="Technical Summary"
        content={data.technical_summary}
      />

      <SummaryCard
        title="Root Cause"
        content={data.root_cause}
      />

      <SummaryCard
        title="MITRE ATT&CK Analysis"
        content={data.mitre_analysis}
      />

      <TimelineCard
        timeline={data.attack_timeline}
      />

      <RecommendationsCard
        title="Containment"
        content={data.containment}
      />

      <RecommendationsCard
        title="Remediation"
        content={data.remediation}
      />

    </div>
  );
}