import AlertTable from "@/components/alerts/AlertTable";
import { useAlerts } from "@/hooks/useAlerts";

export default function Alerts() {
  const { data, isLoading } = useAlerts();

  if (isLoading) {
    return (
      <div className="text-white">
        Loading alerts...
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">
          Security Alerts
        </h1>

        <p className="text-slate-400">
          Active detections generated by the detection engine.
        </p>
      </div>

      <AlertTable
        alerts={data ?? []}
      />
    </div>
  );
}